import 'dart:ui';

import 'package:flutter/material.dart';

// Семантические алиасы
// Пополняютсфя по мере необходимости
// Используют только основную палитру

Color primaryColor = _midnightExpress,
    colorAccent = _sunsetOrange,
    colorError = _sunsetOrange,
    colorRed = _sunsetOrange,
    btnColor = _sunsetOrange,
    secondaryBtnColor = _alizarin_10,
    hintColor = _darkGrey,
    secondaryColor = _darkGrey,
    darkSecondaryColor = _empress,
    disabledBgColor = _whiteSmoke,
    checkColor = _green,
    backgroundColor = _white,
    scaffoldBackgroundColor = _whiteSmoke,
    appBarColor = _white,
    buttonColorGrey = _greyChateau,
    white = _white,
    black = _black,
    blackButtonColor = _revolver,
    dividerColor = _solitude,
    textColorSecondary = _darkGrey,
    textColorSecondaryDark = _darkGrey,
    textColorPrimary = _blackPearl,
    textColorRed = _sunsetOrange,
    textColorError = colorError,
    textColorGrey = _grey,
    textColorGreen = _green,
    textColorBlue = _sanMarino,
    textColorBlack = _black,
    textColorWhite = _white,
    textColorOrange = _orange,
    textColorGreyChateau = _greyChateau,
    textColorNewMidnightBlue = _newMidnightBlue,
    textColorOpaqueGray = _opaqueGray,
    transparent = Colors.transparent,
    onboardingIndicatorThumbColor = _nepal,
    onboardingIndicatorTrackColor = _nepal.withOpacity(0.4),
    onboardingIllustrationBackgroundColor = _ghostWhite,
    onboardingContentBackgroundColor = _white,
    backgroundGradientLightColor = _eastBay,
    backgroundGradientFillColor = _lightMidnightExpress,
    backgroundGradientErrorLightColor = _finn,
    backgroundGradientErrorFillColor = _bordeaux,
    pinEnteringKeyboardBtnBorderColor = _ghostWhite.withOpacity(0.3),
    pinEnteringKeyboardBtnColor = _white,
    pinEnteringKeyboardBtnPressedColor = _greyChateau,
    aliceBlueColor = _aliceBlue;

// Основная палитра (http://www.color-blindness.com/color-name-hue/)
const Color _green = Color(0xFF48AD41),
    _orange = Color(0xFFFF8C00),
    _alizarin_10 = Color(0xFFF8E4E5),
    _white = Colors.white,
    _black = Colors.black,
    _revolver = Color(0xFF35353B),
    _solitude = Color(0xFFE5E8EB),
    _darkGrey = Color(0xFFA7A7A7),
    _whiteSmoke = Color(0xFFF0F0F0),
    _grey = Color(0x8A000000),
    _greyChateau = Color(0xFF95989A),
    _empress = Color(0xFF757575),
    _nepal = Color(0xFF95A3B4),
    _blackPearl = Color(0xFF1D212B),
    _sanMarino = Color(0xFF566EAA),
    _ghostWhite = Color(0xFFF0F3FE),
    _sunsetOrange = Color(0xFFF64141),
    _midnightExpress = Color(0xFF1C2033),
    _eastBay = Color(0xFF4E5572),
    _lightMidnightExpress = Color(0xFF262B42),
    _newMidnightBlue = Color(0xFF007AFF),
    _finn = Color(0xFF623F4C),
    _bordeaux = Color(0xFF4F1E20),
    _aliceBlue = Color(0xFFF9FCFF),
    _opaqueGray = Color(0x40000000);
